### ISSUE TITLE
Kit from Heise

### ISSUE THREAD

**Issue by supertobi** [NikolaiRadke/Nokolino_pcb#1]
I open this question as issue to make it easier to track. Are there any news about the Kit from heise?
In the PCB.md you wrote on 12 May:
"Wait some days longer. The heise Verlag will sell complete NOKOlino kits for an accurate price. Stay tuned for more information."

**Comment by NikolaiRadke** [comment]
Good question. Technically, it is ready to be released. I just wrote an email to heise. Last month we agreed to offer the kit early enough before Christmas.

**Comment by NikolaiRadke** [comment]
Hello supertobi,

sorry for my late answer. Real life work demanded it's tribute...
Sadly, heise can't release the kit before 2019.

If you need PCBs or Modules, feel free to write me an Email.
kontakt@nikolairadke.de

**Comment by NikolaiRadke** [comment]
Alas, they won't sell the kit anymore. I am looking for other ways to sell the kits on my own. Sorry.

**Comment by NikolaiRadke** [comment]
Hello supertobi!
Finally, the kit is available, including tools and online workshop access. Look here, if you are still interested: https://maker-faire.de/workshops/bauset-workshops
