### ISSUE TITLE
gerber: drill map is not matched with drill

### ISSUE THREAD

**Issue by Respekt1** [NikolaiRadke/Nokolino_pcb#2]
Please see attached image. Drill map is not matched with drill file. For pcb production i used the drill file.
Because of missmatching, please regenerate drill map or delete it.

![2019-04-16_drill_map](https://user-images.githubusercontent.com/12272957/56271922-dfd65680-60f9-11e9-8cd7-016981ce2606.jpg)

**Comment by NikolaiRadke** [comment]
Thanks for the hint and sorry for the issue. As you suggested, i've removed the ancient drill map.I ordered my PCBs online at www.jlcpcb.com, the drill map has never been an issue there. 

Yesterday i ordered another set of an upcoming version. You can now change the speech set via external USB. I haven't recieved the shippment yet, so it is untested. But if you are interested, take a look at directory /schematics/V3 - there you can find the new - drill map-free - gerber files. A new software is required, it is located in src/NOKOlino_3.

When the new PCBs are tested, i will update the repository and wiki.
